# [MODEL: 70B]  Traži logičke greške, bugove i security propuste

"""Logic analysis agent for deep code review (security, bugs, logic).

This agent uses Llama 3.3 70B (MODEL_HEAVY) for in-depth analysis of code diffs.
It focuses on logical errors, security vulnerabilities, and critical bugs.
"""

import os
import logging
from dotenv import load_dotenv
from langchain_groq import ChatGroq
from core.state import AgentState
from utils.common import LOGIC_PROMPT

load_dotenv()

logger = logging.getLogger(__name__)


def logic_node(state: AgentState) -> dict:
    """Analyzes code for logic bugs, security issues, and critical errors.

    Args:
            state: The shared AgentState containing pr_diff to analyze.

    Returns:
            A dict with 'logic_comments' key containing a list of formatted
            logic/security/bug findings, ready to append to the shared state via operator.add.

    Example:
            >>> state = {"pr_diff": "diff...", "logic_comments": [], ...}
            >>> result = logic_node(state)
            >>> result["logic_comments"]
            ["**Generated by Multi-Agent PR Review System - Logic Agent**\n...", ...]
    """
    try:
        pr_diff = state.get("pr_diff", "")
        if not pr_diff:
            logger.warning("logic_node: No PR diff provided")
            return {"logic_comments": []}

        # Use the heavy model (Llama 3.3 70B)
        model_name = os.getenv("MODEL_HEAVY", "llama-3.3-70b-versatile")
        llm = ChatGroq(temperature=0, model_name=model_name)

        user_prompt = f"""Analyze the following code for logic, security, and bug issues:

        {pr_diff}

        Apply the logic review guidelines and provide findings in JSON format."""

        messages = [
            {"role": "system", "content": LOGIC_PROMPT},
            {"role": "user", "content": user_prompt},
        ]

        response = llm.invoke(messages)
        response_text = response.content

        logger.info("logic_node: Analysis completed successfully")
        return {"logic_comments": [response_text]}

    except Exception as e:
        logger.error(f"logic_node: Error during analysis - {e}")
        error_comment = f"**Logic Agent Error**: {str(e)}"
        return {"logic_comments": [error_comment]}
